### PR TITLE
view salons on map

### PR DESCRIPTION
**Pull request by bblia**
@terraoldham @alexritchey

### CODE REVIEW

**Comment by terraoldham** [comment]
do you think we could change the tint to our green?

**Comment by bblia** [comment]
@terraoldham i can add that in later, i have to look into how to do it :) it can be part of our polish sprint

**Comment by terraoldham** [comment]
Yuppppp

**Comment by terraoldham** [comment]
lgtm

**Comment by bblia** [comment]
I have to look into how to do that, maybe we can do that as polish? I think
in lab today we will go over custom pins

**Pull request merged**
